dangular/accounts/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    # '/register/'
    path('register', views.register, name='register')
]

dangular/dangular/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
    path('accounts/', include('accounts.urls'))
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

dangular/music/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = 'music'

urlpatterns = [
    # '/music/'
    path('', views.index, name='index'),
    # '/music/3'
    re_path('(?P<album_id>[0-9]+)/', views.album_detail, name='detail'),
    # '/music/favourites'
    re_path('(?P<album_id>[0-9]+)/favourite', views.favourite, name='favourite'),
]

dangular/accounts/models.py
from django.db import models

# Create your models here.

dangular/music/models.py
from django.db import models


class Albums(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)
    price = models.IntegerField()
    description = models.TextField()
    is_liked = models.BooleanField(default=False)
    img = models.ImageField(upload_to='images')
    

     # string representation of Albums
    def __str__(self):
        return self.artist + ' - ' + self.album_title + '-' 

class Song(models.Model):
    album = models.ForeignKey(Albums, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favourite = models.BooleanField(default=False)

    # string representation of Songs
    def __str__(self):
        return self.file_type + '-' + self.song_title

dangular/scrum/models.py
# from django.db import models


# Create your models here.
# class List(models.Models):
#     name = models.CharField(max_length = 50)
#
# class Card(models.Models):
#     name = models.CharField(max_length = 100)
#     description = models.TextField(blank = True)

dangular/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth

# Create your views here.

def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        user_name = request.POST['user_name']
        email = request.POST['email']
        password1 = request.POST['password1']
        # password2 = request.POST['passw0rd2']

        user = User.objects.create_user(username = user_name ,first_name = first_name , last_name = last_name, email = email, password = password1)
        user.save()
        print('created')
        return redirect('/')
    else:
        return render (request, 'register.html')

    

dangular/dangular/views.py
from django.http import HttpResponse
from django.shortcuts import render
from music.models import Albums


def home(request):
    return HttpResponse('Hello World')

def index(request):
    all_albums = Albums.objects.all()
    context = {
        'all_albums' : all_albums
    }
    return render(request , 'index.html', context)

dangular/music/views.py
# from django.http import HttpResponse, Http404
from django.core.mail.backends import console

from .models import Albums, Song
# from django.template import loader
from django.shortcuts import render, get_object_or_404

# template loading using django loader
# def index(request):
#     all_albums = Albums.objects.all()
#     # html = ''
#     # for album in all_albums:
#     #     url = '/music/' + str(album.id) + '/'
#     #     html += '<a href="' + url + '">' + album.album_title+'</a><br>'
#     template = loader.get_template('music/index.html')
#     context = {
#         "all_albums": all_albums,
#     }
#     return HttpResponse(template.render(context, request))


# render template using django shortcuts
def index(request):
    all_albums = Albums.objects.all()
    context = {'all_albums': all_albums}
    return render(request, 'music/index.html', context)


# function with try catch to handle exception
# def album_detail(request, album_id):
#     try:
#         album = Albums.objects.get(id=album_id)
#     except Albums.DoesNotExist:
#         raise Http404("Album doesnt exists")
#     return render(request, 'music/detail.html', {'album': album})


def album_detail(request, album_id):
    album = get_object_or_404(Albums, pk=album_id)
    return render(request, 'music/detail.html', {'album': album})


def favourite(request, album_id):
    album = get_object_or_404(Albums, pk=album_id)
    try:
        selected_songs = album.song_set.get(pk=request.POST['song'])
        print(selected_songs)
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {
            'album': album,
            'error_message': 'select a valid song'
        })
    else:
        # selected_songs.s
        selected_songs.is_favourite = True
        selected_songs.save
        return render(request, 'music/detail.html', {'album': album})

dangular/scrum/views.py
from django.shortcuts import render

# Create your views here.

dangular/music/templates/music/detail.html
<img src="{{ album.album_logo }}" alt="imagename">
<h1>{{ album.album_title }}</h1>
<h3>{{ album.artist }}</h3>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action=" {% url 'music:favourite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
        <label for="song{{ forloop.counter }}">
            {{ song.song_title }}
            {% if song.is_favourite %}
                <img src="https://d1nhio0ox7pgb.cloudfront.net/_img/g_collection_png/standard/512x512/star.png">
            {% endif %}
        </label><br>
    {% endfor %}
    <input type="submit" value="Favourite">
</form>

dangular/music/templates/music/index.html
{% extends 'base.html' %}

{% block content %}
{% if all_albums %}
    <ul>
        {% for album in all_albums %}
<!--            <li><a href="music/{{album.id}}">{{album.album_title}}</a></li>-->
            <li><a href="{% url 'music:detail' album.id %}">{{album.album_title}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h2>NO Album available</h2>
{% endif %}
{% endblock %}

dangular/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dango Project</title>
</head>
<body bgcolor="cyan">
{% block content %}

{% endblock %}

</body>
</html>

dangular/templates/index.html
{% load static %}
{% static "img" as baseurl%}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Music</title>
<!--

Template 2101 Insertion

http://www.tooplate.com/view/2101-insertion

-->
  <!-- load CSS -->
  <link rel="stylesheet" href="{% static 'https://fonts.googleapis.com/css?family=Open+Sans:300,400' %}">        <!-- Google web font "Open Sans" -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">                                            <!-- https://getbootstrap.com/ -->
  <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">                                      <!-- Font awesome -->
  <link rel="stylesheet" href="{% static 'css/tooplate-style.css' %}">                                           <!-- Templatemo style -->

  <script>
    var renderPage = true;

    if (navigator.userAgent.indexOf('MSIE') !== -1
      || navigator.appVersion.indexOf('Trident/') > 0) {
      /* Microsoft Internet Explorer detected in. */
      alert("Please view this in a modern browser such as Chrome or Microsoft Edge.");
      renderPage = false;
    }
  </script>

</head>

<body>

  <!-- Loader -->
  <div id="loader-wrapper">
    <div id="loader"></div>
    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>
  </div>

  <div class="tm-main">

    <div class="tm-welcome-section">
      <div class="container tm-navbar-container">
        <div class="row">
          <div class="col-xl-12">
            <nav class="navbar navbar-expand-sm">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                  <a href="index.html" class="nav-link tm-nav-link tm-text-white active">Home</a>
                </li>
                <li class="nav-item">
                  <a href="about.html" class="nav-link tm-nav-link tm-text-white">About</a>
                </li>
                <li class="nav-item">
                  <a href="accounts/register" class="nav-link tm-nav-link tm-text-white">Register</a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>

      <div class="container text-center tm-welcome-container">
        <div class="tm-welcome">
          <i class="fas tm-fa-big fa-music tm-fa-mb-big"></i>
          <h1 class="text-uppercase mb-3 tm-site-name">Insertion</h1>
          <p class="tm-site-description">New HTML Website Template</p>
        </div>
      </div>

    </div>

    <div class="container">
      <div class="tm-search-form-container">
        <form action="index.html" method="GET" class="form-inline tm-search-form">
          <div class="text-uppercase tm-new-release">New Release</div>
          <div class="form-group tm-search-box">
            <input type="text" name="keyword" class="form-control tm-search-input" placeholder="Type your keyword ...">
            <input type="submit" value="Search" class="form-control tm-search-submit">
          </div>
          <div class="form-group tm-advanced-box">
            <a href="#" class="tm-text-white">Go Advanced ...</a>
          </div>
        </form>
      </div>
<!-- Album section -->

      <div class="row tm-albums-container grid">
        <div class="col-sm-12 col-12 col-md-12 col-lg-12 col-xl-12">
          <h3>Latest Albums</h3>
        </div>
        {% for album in all_albums %}
        <div class="col-sm-6 col-12 col-md-6 col-lg-3 col-xl-3 tm-album-col">
          <figure class="effect-sadie">
            <img src="{{album.img.url}}" alt="Image" class="img-fluid">
            <figcaption>
              <h2>{{ album.album_title }}</h2>
              <p>{{ album.description }}</p>
            </figcaption>
          </figure>
        </div>
        {% endfor %}
        <!-- <div class="col-sm-6 col-12 col-md-6 col-lg-3 col-xl-3 tm-album-col">
          <figure class="effect-sadie">
            <img src="{% static 'img/insertion-260x390-04.jpg' %}" alt="Image" class="img-fluid">
            <figcaption>
              <h2>Album Four</h2>
              <p>Praesent nec feugiat dolor, elementum mollis purus. Etiam faucibus.</p>
            </figcaption>
          </figure>
        </div>  -->
      </div>     
      <!-- end repetition -->
      <div class="row">
        <div class="col-lg-12">
          <div class="tm-tag-line">
          <h2 class="tm-tag-line-title">Music is your powerful energy.</h2>
          </div>
        </div>
      </div>

      <div class="row mb-5">
        <div class="col-xl-12">
          <div class="media-boxes">
            <!-- featuring Albums -->
            <div class="media">
              <img src="{% static 'img/insertion-140x140-01.jpg' %}" alt="Image" class="mr-3">
              <div class="media-body tm-bg-gray">
                <div class="tm-description-box">
                  <h5 class="tm-text-blue">Vivamus eget urna vitae ante</h5>
                  <p class="mb-0">Insertion HTML Template includes 3 different pages. You can use this layout for your website. Please tell your friends about <a href="{% static 'https://plus.google.com/+tooplate' %}" target="_parent">Tooplate</a>. Thank you.</p>
                </div>
                <div class="tm-buy-box">
                  <a href="#" class="tm-bg-blue tm-text-white tm-buy">buy</a>
                  <span class="tm-text-blue tm-price-tag">$5.50</span>
                </div>
              </div>
            </div>

            <div class="media">
              <img src="{% static 'img/insertion-140x140-02.jpg' %}" alt="Image" class="mr-3">
              <div class="media-body tm-bg-pink-light">
                <div class="tm-description-box">
                  <h5 class="tm-text-pink">Proin fermentum sapien sed nisl</h5>
                  <p class="mb-0">Donec est felis, posuere viverra dapibus ac, pretium vel libero. Aliquam consectetur, arcu eget euismod congue, tortor metus vehicula.</p>
                </div>
                <div class="tm-buy-box">
                  <a href="#" class="tm-bg-pink tm-text-white tm-buy">buy</a>
                  <span class="tm-text-pink tm-price-tag">$7.25</span>
                </div>
              </div>
            </div>

            <div class="media">
              <img src="{% static 'img/insertion-140x140-03.jpg' %}" alt="Image" class="mr-3">
              <div class="media-body tm-bg-gray">
                <div class="tm-description-box">
                  <h5 class="tm-text-blue">Quisque dignissim porta nunc</h5>
                  <p class="mb-0">In neque felis, fringilla vel orci ut, sodales consectetur purus. Vivamus eget urna vitae ante pellentesque iaculis. Praesent sit amet.</p>
                </div>
                <div class="tm-buy-box">
                  <a href="#" class="tm-bg-blue tm-text-white tm-buy">buy</a>
                  <span class="tm-text-blue tm-price-tag">$6.80</span>
                </div>
              </div>
            </div>

            <div class="media">
              <img src="{% static 'img/insertion-140x140-04.jpg' %}" alt="Image" class="mr-3">
              <div class="media-body tm-bg-pink-light">
                <div class="tm-description-box">
                  <h5 class="tm-text-pink">Vestibulum mattis quam sodales</h5>
                  <p class="mb-0">Curabitur id tempor orci. Fusce efficitur in enim sit amet sodales. Proin id gravida leo. Phasellus non quam et justo faucibus rhoncus.</p>
                </div>
                <div class="tm-buy-box">
                  <a href="#" class="tm-bg-pink tm-text-white tm-buy">buy</a>
                  <span class="tm-text-pink tm-price-tag">$3.75</span>
                </div>
              </div>
            </div>
            <!-- end of featuring boxes -->
          </div> <!-- media-boxes -->
        </div>
      </div>

      <div class="row tm-mb-big tm-subscribe-row">
        <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 tm-bg-gray tm-subscribe-form">
          <h3 class="tm-text-pink tm-mb-30">Subscribe our updates!</h3>
          <p class="tm-mb-30">Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi semper, ligula et pretium porttitor, leo orci accumsan ligula.</p>
          <form action="index.html" method="POST">
            <div class="form-group mb-0">
              <input type="text" class="form-control tm-subscribe-input" placeholder="Your Email">
              <input type="submit" value="Submit" class="tm-bg-pink tm-text-white d-block ml-auto tm-subscribe-btn">
            </div>
          </form>
        </div>
        <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 img-fluid pl-0 tm-subscribe-img"></div>
      </div>

      <div class="row tm-mb-medium">
        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 mb-4">
          <h4 class="mb-4 tm-font-300">Latest Albums</h4>
          <a href="#" class="tm-text-blue-dark d-block mb-2">Sed fringilla consectetur</a>
          <a href="#" class="tm-text-blue-dark d-block mb-2">Mauris porta nisl quis</a>
          <a href="#" class="tm-text-blue-dark d-block mb-2">Quisque maximus quam nec</a>
          <a href="#" class="tm-text-blue-dark d-block">Class aptent taciti sociosqu ad</a>
        </div>
        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 mb-4">
          <h4 class="mb-4 tm-font-300">Our Pages</h4>
          <a href="#" class="tm-text-blue-dark d-block mb-2">Nam dapibus imperdiet</a>
          <a href="#" class="tm-text-blue-dark d-block mb-2">Primis in faucibus orci</a>
          <a href="#" class="tm-text-blue-dark d-block mb-2">Sed interdum blandit dictum</a>
          <a href="#" class="tm-text-blue-dark d-block">Donec non blandit nisl</a>
        </div>
        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6">
          <h4 class="mb-4 tm-font-300">Quick Links</h4>
          <a href="#" class="tm-text-blue-dark d-block mb-2">Nullam scelerisque mauris</a>
          <a href="#" class="tm-text-blue-dark d-block mb-2">Vivamus tristique enim non orci</a>
          <a href="#" class="tm-text-blue-dark d-block mb-2">Luctus et ultrices posuere</a>
          <a href="#" class="tm-text-blue-dark d-block">Cubilia Curae</a>
        </div>
      </div>
      <footer class="row">
        <div class="col-xl-12">
          <p class="text-center p-4">Copyright &copy; <span class="tm-current-year">2018</span> Your Company Name 
          
          - Design:  Tooplate</p>
        </div>
      </footer>
    </div> <!-- .container -->

  </div> <!-- .main -->

  <!-- load JS -->
  <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script> <!-- https://jquery.com/ -->
  <script>

    /* DOM is ready
    ------------------------------------------------*/
    $(function () {

      if (renderPage) {
        $('body').addClass('loaded');
      }

      $('.tm-current-year').text(new Date().getFullYear());  // Update year in copyright
    });

  </script>
</body>
</html>

dangular/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration</title>
</head>
<body>
    <form action="register" method="POST">
        {% csrf_token %}
        <input type="text" name="first_name" placeholder="First name"><br>
        <input type="text" name="last_name" placeholder="Last name"><br>
        <input type="text" name="user_name" placeholder="User name"><br>
        <input type="email" name="email" placeholder="email"><br>
        <input type="password" name="password1" placeholder="password"><br>
        <input type="password" name="password2" placeholder="confirm password"><br>
        <input type="submit">
    </form>
</body>
</html> 